<?php

use App\Models\Attribute;
use App\Models\Country;
use ME\Hr\Models\BonusPolicy;
use ME\Hr\Models\BonusTitle;
use ME\Hr\Models\Designation;
use ME\Hr\Models\Factory;
use ME\Hr\Models\LeaveInfo;
use ME\Hr\Models\Location;
use ME\Hr\Models\PaymentMethod;
use ME\Hr\Models\ProductionBonus;
use ME\Hr\Models\Requisition;
use ME\Hr\Models\SalaryKey;
use ME\Hr\Models\Shift;
use ME\Hr\Models\SubSection;
use ME\Hr\Models\Weekday;
use ME\Hr\Models\WorkingPlace;

return [
    'route' => [
        'prefix' => 'admin/hr-center',
        'as' => 'hr-center.',
        'middleware' => ['web', 'auth', 'redirectUser'],
    ],
    'legacy_links' => [
        [
            'title' => 'Employee Type',
            'description' => 'HR Center classification setup',
            'url' => '/admin/hr-center/masters/classifications',
        ],
        [
            'title' => 'Block / Line',
            'description' => 'Existing admin line setup',
            'url' => '/admin/hr/floor-lines',
        ],
        [
            'title' => 'Department',
            'description' => 'Existing admin department setup',
            'url' => '/admin/hr/departments',
        ],
        [
            'title' => 'Division',
            'description' => 'Existing admin division setup',
            'url' => '/admin/hr/divisions',
        ],
        [
            'title' => 'Grade',
            'description' => 'Existing admin grade setup',
            'url' => '/admin/hr/grades',
        ],
        [
            'title' => 'Section',
            'description' => 'Existing admin section setup',
            'url' => '/admin/hr/sections',
        ],
    ],
    'entities' => [
        'classifications' => [
            'title' => 'Classification',
            'model' => Attribute::class,
            'search' => ['name', 'bn_name'],
            'defaults' => ['type' => 16, 'status' => 'active'],
            'index_fields' => ['name', 'bn_name', 'description', 'status'],
            'fields' => [
                'name' => ['label' => 'Name', 'type' => 'text', 'rules' => 'required|string|max:191'],
                'bn_name' => ['label' => 'Bangla Name', 'type' => 'text', 'rules' => 'nullable|string|max:191'],
                'description' => ['label' => 'Description', 'type' => 'textarea', 'rules' => 'nullable|string|max:1000'],
                'status' => ['label' => 'Status', 'type' => 'select', 'rules' => 'required|in:active,inactive', 'options' => ['active' => 'Active', 'inactive' => 'Inactive']],
            ],
        ],
        'countries' => [
            'title' => 'Country',
            'model' => Country::class,
            'search' => ['name', 'bn_name'],
            'defaults' => ['type' => 1],
            'index_fields' => ['name', 'bn_name'],
            'fields' => [
                'name' => ['label' => 'Name', 'type' => 'text', 'rules' => 'required|string|max:250'],
                'bn_name' => ['label' => 'Bangla Name', 'type' => 'text', 'rules' => 'nullable|string|max:100'],
            ],
        ],
        'divisions' => [
            'title' => 'Division',
            'model' => Country::class,
            'search' => ['name', 'bn_name'],
            'defaults' => ['type' => 2],
            'index_fields' => ['name', 'bn_name'],
            'fields' => [
                'parent_id' => ['label' => 'Country', 'type' => 'select', 'rules' => 'required|integer', 'source' => ['driver' => 'model', 'model' => Country::class, 'conditions' => ['type' => 1], 'label' => 'name']],
                'name' => ['label' => 'Name', 'type' => 'text', 'rules' => 'required|string|max:250'],
                'bn_name' => ['label' => 'Bangla Name', 'type' => 'text', 'rules' => 'nullable|string|max:100'],
            ],
        ],
        'districts' => [
            'title' => 'District',
            'model' => Country::class,
            'search' => ['name', 'bn_name'],
            'defaults' => ['type' => 3],
            'index_fields' => ['name', 'bn_name'],
            'fields' => [
                'parent_id' => ['label' => 'Division', 'type' => 'select', 'rules' => 'required|integer', 'source' => ['driver' => 'model', 'model' => Country::class, 'conditions' => ['type' => 2], 'label' => 'name']],
                'name' => ['label' => 'Name', 'type' => 'text', 'rules' => 'required|string|max:250'],
                'bn_name' => ['label' => 'Bangla Name', 'type' => 'text', 'rules' => 'nullable|string|max:100'],
            ],
        ],
        'police-stations' => [
            'title' => 'Thana',
            'model' => Country::class,
            'search' => ['name', 'bn_name'],
            'defaults' => ['type' => 4],
            'index_fields' => ['name', 'bn_name', 'parent_id'],
            'fields' => [
                'parent_id' => ['label' => 'District', 'type' => 'select', 'rules' => 'required|integer', 'source' => ['driver' => 'model', 'model' => Country::class, 'conditions' => ['type' => 3], 'label' => 'name']],
                'name' => ['label' => 'Name', 'type' => 'text', 'rules' => 'required|string|max:250'],
                'bn_name' => ['label' => 'Bangla Name', 'type' => 'text', 'rules' => 'nullable|string|max:100'],
            ],
        ],
        'marital-statuses' => [
            'title' => 'Marital Status',
            'model' => Location::class,
            'search' => ['name', 'bn_name', 'code'],
            'defaults' => ['type' => 'marital_status', 'status' => 'active'],
            'index_fields' => ['name', 'bn_name', 'code', 'status'],
            'fields' => [
                'name' => ['label' => 'Name', 'type' => 'text', 'rules' => 'required|string|max:191'],
                'bn_name' => ['label' => 'Bangla Name', 'type' => 'text', 'rules' => 'nullable|string|max:191'],
                'code' => ['label' => 'Code', 'type' => 'text', 'rules' => 'nullable|string|max:50'],
                'status' => ['label' => 'Status', 'type' => 'select', 'rules' => 'required|in:active,inactive', 'options' => ['active' => 'Active', 'inactive' => 'Inactive']],
            ],
        ],
        'religions' => [
            'title' => 'Religion',
            'model' => Location::class,
            'search' => ['name', 'bn_name', 'code'],
            'defaults' => ['type' => 'religion', 'status' => 'active'],
            'index_fields' => ['name', 'bn_name', 'code', 'status'],
            'fields' => [
                'name' => ['label' => 'Name', 'type' => 'text', 'rules' => 'required|string|max:191'],
                'bn_name' => ['label' => 'Bangla Name', 'type' => 'text', 'rules' => 'nullable|string|max:191'],
                'code' => ['label' => 'Code', 'type' => 'text', 'rules' => 'nullable|string|max:50'],
                'status' => ['label' => 'Status', 'type' => 'select', 'rules' => 'required|in:active,inactive', 'options' => ['active' => 'Active', 'inactive' => 'Inactive']],
            ],
        ],
        'sexes' => [
            'title' => 'Sex',
            'model' => Location::class,
            'search' => ['name', 'bn_name', 'code'],
            'defaults' => ['type' => 'sex', 'status' => 'active'],
            'index_fields' => ['name', 'bn_name', 'code', 'status'],
            'fields' => [
                'name' => ['label' => 'Name', 'type' => 'text', 'rules' => 'required|string|max:191'],
                'bn_name' => ['label' => 'Bangla Name', 'type' => 'text', 'rules' => 'nullable|string|max:191'],
                'code' => ['label' => 'Code', 'type' => 'text', 'rules' => 'nullable|string|max:50'],
                'status' => ['label' => 'Status', 'type' => 'select', 'rules' => 'required|in:active,inactive', 'options' => ['active' => 'Active', 'inactive' => 'Inactive']],
            ],
        ],
        'bonus-policies' => [
            'title' => 'Bonus Policy',
            'model' => BonusPolicy::class,
            'search' => ['name'],
            'defaults' => ['status' => 'active'],
            'index_fields' => ['name', 'salary_basis', 'amount_type', 'amount', 'status'],
            'fields' => [
                'name' => ['label' => 'Policy Name', 'type' => 'text', 'rules' => 'required|string|max:191'],
                'section_id' => ['label' => 'Section', 'type' => 'select', 'rules' => 'nullable|integer', 'source' => ['driver' => 'attribute', 'filter' => 'sections']],
                'sub_section_id' => ['label' => 'Sub Section', 'type' => 'select', 'rules' => 'nullable|integer', 'source' => ['driver' => 'model', 'model' => SubSection::class, 'label' => 'name']],
                'designation_id' => ['label' => 'Designation', 'type' => 'select', 'rules' => 'nullable|integer', 'source' => ['driver' => 'attribute', 'filter' => 'designation']],
                'month_from' => ['label' => 'Month Range From', 'type' => 'date', 'rules' => 'nullable|date'],
                'month_to' => ['label' => 'Month Range To', 'type' => 'date', 'rules' => 'nullable|date'],
                'salary_basis' => ['label' => 'Basic / Gross / Production', 'type' => 'select', 'rules' => 'required|in:basic,gross,production', 'options' => ['basic' => 'Basic', 'gross' => 'Gross', 'production' => 'Production']],
                'amount_type' => ['label' => 'Percent / Fixed', 'type' => 'select', 'rules' => 'required|in:percent,fixed', 'options' => ['percent' => 'Percent', 'fixed' => 'Fixed']],
                'amount' => ['label' => 'Amount', 'type' => 'number', 'rules' => 'required|numeric|min:0', 'step' => '0.01'],
                'status' => ['label' => 'Status', 'type' => 'select', 'rules' => 'required|in:active,inactive', 'options' => ['active' => 'Active', 'inactive' => 'Inactive']],
            ],
        ],
        'bonus-titles' => [
            'title' => 'Bonus Title',
            'model' => BonusTitle::class,
            'search' => ['title', 'bn_title', 'code'],
            'defaults' => ['status' => 'active'],
            'index_fields' => ['title', 'bn_title', 'code', 'status'],
            'fields' => [
                'title' => ['label' => 'Title', 'type' => 'text', 'rules' => 'required|string|max:191'],
                'bn_title' => ['label' => 'Bangla Title', 'type' => 'text', 'rules' => 'nullable|string|max:191'],
                'code' => ['label' => 'Code', 'type' => 'text', 'rules' => 'nullable|string|max:50'],
                'description' => ['label' => 'Description', 'type' => 'textarea', 'rules' => 'nullable|string'],
                'status' => ['label' => 'Status', 'type' => 'select', 'rules' => 'required|in:active,inactive', 'options' => ['active' => 'Active', 'inactive' => 'Inactive']],
            ],
        ],
        'designations' => [
            'title' => 'Designation',
            'model' => Designation::class,
            'search' => ['name', 'bn_name'],
            'defaults' => ['status' => 'active'],
            'index_fields' => ['name', 'bn_name', 'department_id', 'section_id', 'grade_id', 'status'],
            'fields' => [
                'name' => ['label' => 'Name', 'type' => 'text', 'rules' => 'required|string|max:191'],
                'bn_name' => ['label' => 'Bangla Name', 'type' => 'text', 'rules' => 'nullable|string|max:191'],
                'grade_id' => ['label' => 'Grade', 'type' => 'select', 'rules' => 'nullable|integer', 'source' => ['driver' => 'attribute', 'filter' => 'grades']],
                'approved_manpower' => ['label' => 'Approved Manpower', 'type' => 'number', 'rules' => 'nullable|integer|min:0'],
                'department_id' => ['label' => 'Department', 'type' => 'select', 'rules' => 'nullable|integer', 'source' => ['driver' => 'attribute', 'filter' => 'department']],
                'section_id' => ['label' => 'Section', 'type' => 'select', 'rules' => 'nullable|integer', 'source' => ['driver' => 'attribute', 'filter' => 'sections']],
                'attendance_bonus' => ['label' => 'Attendance Bonus', 'type' => 'number', 'rules' => 'nullable|numeric|min:0', 'step' => '0.01'],
                'attendance_bonus_com' => ['label' => 'Attendance Bonus Com.', 'type' => 'number', 'rules' => 'nullable|numeric|min:0', 'step' => '0.01'],
                'tiffin_allowance' => ['label' => 'Tiffin Allowance', 'type' => 'number', 'rules' => 'nullable|numeric|min:0', 'step' => '0.01'],
                'minimum_tiffin_hour' => ['label' => 'Minimum Tiffin Hour', 'type' => 'number', 'rules' => 'nullable|numeric|min:0', 'step' => '0.01'],
                'night_allowance' => ['label' => 'Night Allowance', 'type' => 'number', 'rules' => 'nullable|numeric|min:0', 'step' => '0.01'],
                'minimum_night_hour' => ['label' => 'Minimum Night Hour', 'type' => 'number', 'rules' => 'nullable|numeric|min:0', 'step' => '0.01'],
                'dinner_allowance' => ['label' => 'Dinner Allowance', 'type' => 'number', 'rules' => 'nullable|numeric|min:0', 'step' => '0.01'],
                'minimum_dinner_hour' => ['label' => 'Minimum Dinner Hour', 'type' => 'number', 'rules' => 'nullable|numeric|min:0', 'step' => '0.01'],
                'meal_payment_way' => ['label' => 'Tiffin, Night & Dinner Payment Way', 'type' => 'select', 'rules' => 'nullable|in:daily,monthly', 'options' => ['daily' => 'Daily', 'monthly' => 'Monthly']],
                'weekend_allowance_count' => ['label' => 'Weekend Allowance Count', 'type' => 'select', 'rules' => 'nullable|in:gross_month_day,basic_working_day,basic_104_2_5', 'options' => ['gross_month_day' => 'gross/monthDay', 'basic_working_day' => 'basic/working day', 'basic_104_2_5' => 'basic/104*2.5']],
                'holiday_allowance' => ['label' => 'Holiday Allowance', 'type' => 'number', 'rules' => 'nullable|numeric|min:0', 'step' => '0.01'],
                'is_ot_basis_wphp' => ['label' => 'Is OT Basis (WPHP)', 'type' => 'checkbox', 'rules' => 'nullable|boolean'],
                'is_ot_basis_main' => ['label' => 'Is OT Basis (Main)', 'type' => 'checkbox', 'rules' => 'nullable|boolean'],
                'is_ot_basis_others_1' => ['label' => 'Is OT Basis (Others-1)', 'type' => 'checkbox', 'rules' => 'nullable|boolean'],
                'is_ot_basis_others_2' => ['label' => 'Is OT Basis (Others-2)', 'type' => 'checkbox', 'rules' => 'nullable|boolean'],
                'responsibilities' => ['label' => 'Responsibilities', 'type' => 'textarea', 'rules' => 'nullable|string'],
                'report_to' => ['label' => 'Report To', 'type' => 'select', 'rules' => 'nullable|integer', 'source' => ['driver' => 'user', 'label' => 'name']],
                'follow_up_team' => ['label' => 'Follow Up Team', 'type' => 'textarea', 'rules' => 'nullable|string'],
                'status' => ['label' => 'Status', 'type' => 'select', 'rules' => 'required|in:active,inactive', 'options' => ['active' => 'Active', 'inactive' => 'Inactive']],
            ],
        ],
        'factories' => [
            'title' => 'Factory',
            'model' => Factory::class,
            'search' => ['name', 'bn_name', 'address', 'bn_address'],
            'defaults' => ['status' => 'active'],
            'index_fields' => ['factory_no', 'name', 'bn_name', 'address', 'bn_address', 'weekend', 'status'],
            'fields' => [
                'factory_no' => ['label' => 'No. of Factory', 'type' => 'text', 'rules' => 'nullable|string|max:50'],
                'is_running' => ['label' => 'Is A~Z Running', 'type' => 'checkbox', 'rules' => 'nullable|boolean'],
                'name' => ['label' => 'Name', 'type' => 'text', 'rules' => 'required|string|max:191'],
                'bn_name' => ['label' => 'Bangla Name', 'type' => 'text', 'rules' => 'nullable|string|max:191'],
                'address' => ['label' => 'Address', 'type' => 'textarea', 'rules' => 'nullable|string'],
                'bn_address' => ['label' => 'Bangla Address', 'type' => 'textarea', 'rules' => 'nullable|string'],
                'contact_number' => ['label' => 'Contact Number', 'type' => 'text', 'rules' => 'nullable|string|max:50'],
                'email' => ['label' => 'Email', 'type' => 'email', 'rules' => 'nullable|email|max:191'],
                'website' => ['label' => 'Website', 'type' => 'url', 'rules' => 'nullable|url|max:191'],
                'weekend' => ['label' => 'Weekend', 'type' => 'text', 'rules' => 'nullable|string|max:50'],
                'roster_day' => ['label' => 'Roster Day', 'type' => 'text', 'rules' => 'nullable|string|max:50'],
                'stamp_amount' => ['label' => 'Stamp Amount', 'type' => 'number', 'rules' => 'nullable|numeric|min:0', 'step' => '0.01'],
                'attendance_bonus_late_days_more_than' => ['label' => 'Attendance Bonus Cut After Late Days', 'type' => 'number', 'rules' => 'nullable|integer|min:0'],
                'ot_rate' => ['label' => 'OT Rate', 'type' => 'number', 'rules' => 'nullable|numeric|min:0', 'step' => '0.01'],
                'absent_deduct_from' => ['label' => 'Absent Deduct From', 'type' => 'text', 'rules' => 'nullable|string|max:191'],
                'absent_deduct_special' => ['label' => 'Absent Deduct Special', 'type' => 'text', 'rules' => 'nullable|string|max:191'],
                'production_subsidy' => ['label' => 'Pro. Subsidy', 'type' => 'number', 'rules' => 'nullable|numeric|min:0', 'step' => '0.01'],
                'attendance_id_type' => ['label' => 'Attendance ID Type', 'type' => 'text', 'rules' => 'nullable|string|max:191'],
                'attendance_type' => ['label' => 'Attendance Type', 'type' => 'text', 'rules' => 'nullable|string|max:191'],
                'last_earn_leave_count_date' => ['label' => 'Last Earn Leave Count Date', 'type' => 'date', 'rules' => 'nullable|date'],
                'authority_sign' => ['label' => 'Authority Sign', 'type' => 'text', 'rules' => 'nullable|string|max:191'],
                'apply_special_office_time_in_main' => ['label' => 'Apply Special Office Time In Main', 'type' => 'checkbox', 'rules' => 'nullable|boolean'],
                'status' => ['label' => 'Status', 'type' => 'select', 'rules' => 'required|in:active,inactive', 'options' => ['active' => 'Active', 'inactive' => 'Inactive']],
            ],
        ],
        'leave-infos' => [
            'title' => 'Leave Info',
            'model' => LeaveInfo::class,
            'search' => ['name', 'code'],
            'defaults' => ['status' => 'active'],
            'index_fields' => ['name', 'code', 'days', 'status'],
            'fields' => [
                'name' => ['label' => 'Name', 'type' => 'text', 'rules' => 'required|string|max:191'],
                'code' => ['label' => 'Code', 'type' => 'text', 'rules' => 'required|string|max:50'],
                'days' => ['label' => 'Days', 'type' => 'number', 'rules' => 'required|integer|min:0'],
                'description' => ['label' => 'Description', 'type' => 'textarea', 'rules' => 'nullable|string'],
                'status' => ['label' => 'Status', 'type' => 'select', 'rules' => 'required|in:active,inactive', 'options' => ['active' => 'Active', 'inactive' => 'Inactive']],
            ],
        ],
        'production-bonuses' => [
            'title' => 'Production Bonus',
            'model' => ProductionBonus::class,
            'search' => ['name'],
            'defaults' => ['status' => 'active'],
            'index_fields' => ['name', 'section_id', 'percentage', 'status'],
            'fields' => [
                'name' => ['label' => 'Name', 'type' => 'text', 'rules' => 'required|string|max:191'],
                'section_id' => ['label' => 'Section', 'type' => 'select', 'rules' => 'nullable|integer', 'source' => ['driver' => 'attribute', 'filter' => 'sections']],
                'sub_section_id' => ['label' => 'Sub Section', 'type' => 'select', 'rules' => 'nullable|integer', 'source' => ['driver' => 'model', 'model' => SubSection::class, 'label' => 'name']],
                'percentage' => ['label' => 'Percentage', 'type' => 'number', 'rules' => 'required|numeric|min:0', 'step' => '0.01'],
                'effective_from' => ['label' => 'Effective From', 'type' => 'date', 'rules' => 'nullable|date'],
                'effective_to' => ['label' => 'Effective To', 'type' => 'date', 'rules' => 'nullable|date'],
                'status' => ['label' => 'Status', 'type' => 'select', 'rules' => 'required|in:active,inactive', 'options' => ['active' => 'Active', 'inactive' => 'Inactive']],
            ],
        ],
        'salary-keys' => [
            'title' => 'Salary Key',
            'model' => SalaryKey::class,
            'search' => ['name'],
            'defaults' => ['name' => 'Default Salary Key', 'status' => 'active'],
            'index_fields' => ['name', 'payment_date', 'status'],
            'fields' => [
                'name' => ['label' => 'Name', 'type' => 'text', 'rules' => 'required|string|max:191'],
                'medical' => ['label' => 'Medical', 'type' => 'number', 'rules' => 'nullable|numeric|min:0', 'step' => '0.01'],
                'lunch' => ['label' => 'Lunch', 'type' => 'number', 'rules' => 'nullable|numeric|min:0', 'step' => '0.01'],
                'transport' => ['label' => 'Transport', 'type' => 'number', 'rules' => 'nullable|numeric|min:0', 'step' => '0.01'],
                'salary_approved_person_1' => ['label' => 'Salary Approved Person-1', 'type' => 'select', 'rules' => 'nullable|integer', 'source' => ['driver' => 'user', 'label' => 'name']],
                'salary_approved_person_2' => ['label' => 'Salary Approved Person-2', 'type' => 'select', 'rules' => 'nullable|integer', 'source' => ['driver' => 'user', 'label' => 'name']],
                'salary_approved_person_3' => ['label' => 'Salary Approved Person-3', 'type' => 'select', 'rules' => 'nullable|integer', 'source' => ['driver' => 'user', 'label' => 'name']],
                'salary_approved_person_4' => ['label' => 'Salary Approved Person-4', 'type' => 'select', 'rules' => 'nullable|integer', 'source' => ['driver' => 'user', 'label' => 'name']],
                'salary_approved_person_5' => ['label' => 'Salary Approved Person-5', 'type' => 'select', 'rules' => 'nullable|integer', 'source' => ['driver' => 'user', 'label' => 'name']],
                'payment_date' => ['label' => 'Payment Date', 'type' => 'date', 'rules' => 'nullable|date'],
                'status' => ['label' => 'Status', 'type' => 'select', 'rules' => 'required|in:active,inactive', 'options' => ['active' => 'Active', 'inactive' => 'Inactive']],
            ],
        ],
        'payment-methods' => [
            'title' => 'Payment Method',
            'model' => PaymentMethod::class,
            'search' => ['name', 'code'],
            'defaults' => ['status' => 'active'],
            'index_fields' => ['name', 'code', 'status'],
            'fields' => [
                'name' => ['label' => 'Name', 'type' => 'text', 'rules' => 'required|string|max:191'],
                'code' => ['label' => 'Code', 'type' => 'text', 'rules' => 'nullable|string|max:50'],
                'description' => ['label' => 'Description', 'type' => 'textarea', 'rules' => 'nullable|string'],
                'status' => ['label' => 'Status', 'type' => 'select', 'rules' => 'required|in:active,inactive', 'options' => ['active' => 'Active', 'inactive' => 'Inactive']],
            ],
        ],
        'shifts' => [
            'title' => 'Shift',
            'model' => Shift::class,
            'search' => ['name_of_shift', 'name_of_shift_bn'],
            'defaults' => ['status' => 'active'],
            'index_fields' => ['name_of_shift', 'shift_starting_time', 'shift_closing_time', 'status'],
            'fields' => [
                'name_of_shift' => ['label' => 'Name', 'type' => 'text', 'rules' => 'required|string|max:191'],
                'name_of_shift_bn' => ['label' => 'Bangla Name', 'type' => 'text', 'rules' => 'nullable|string|max:191'],
                'shift_starting_time' => ['label' => 'Start Time', 'type' => 'time', 'rules' => 'required'],
                'shift_closing_time' => ['label' => 'End Time', 'type' => 'time', 'rules' => 'required'],
                'card_accept_from' => ['label' => 'Start Allow Time', 'type' => 'time', 'rules' => 'nullable'],
                'red_marking_on' => ['label' => 'Late Allow Time', 'type' => 'time', 'rules' => 'nullable'],
                'card_accept_to' => ['label' => 'Out Time Start', 'type' => 'time', 'rules' => 'nullable'],
                'status' => ['label' => 'Status', 'type' => 'select', 'rules' => 'required|in:active,inactive', 'options' => ['active' => 'Active', 'inactive' => 'Inactive']],
            ],
        ],
        'sections' => [
            'title' => 'Section',
            'model' => Attribute::class,
            'search' => ['name'],
            'defaults' => ['type' => 29, 'status' => 'active'],
            'index_fields' => ['name', 'parent_id', 'status'],
            'fields' => [
                'name' => ['label' => 'Name', 'type' => 'text', 'rules' => 'required|string|max:191'],
                'parent_id' => ['label' => 'Department', 'type' => 'select', 'rules' => 'nullable|integer', 'source' => ['driver' => 'attribute', 'filter' => 'department']],
                'description' => ['label' => 'Description', 'type' => 'textarea', 'rules' => 'nullable|string'],
                'status' => ['label' => 'Status', 'type' => 'select', 'rules' => 'required|in:active,inactive', 'options' => ['active' => 'Active', 'inactive' => 'Inactive']],
            ],
        ],
        'sub-sections' => [
            'title' => 'Sub Section',
            'model' => SubSection::class,
            'search' => ['name'],
            'defaults' => ['status' => 'active'],
            'index_fields' => ['name', 'department_id', 'section_id', 'salary_type', 'status'],
            'fields' => [
                'name' => ['label' => 'Name', 'type' => 'text', 'rules' => 'required|string|max:191'],
                'department_id' => ['label' => 'Department', 'type' => 'select', 'rules' => 'nullable|integer', 'source' => ['driver' => 'attribute', 'filter' => 'department']],
                'section_id' => ['label' => 'Section', 'type' => 'select', 'rules' => 'nullable|integer', 'source' => ['driver' => 'attribute', 'filter' => 'sections']],
                'salary_type' => ['label' => 'Salary Type', 'type' => 'select', 'rules' => 'required|in:price_rate,fixed_rate', 'options' => ['price_rate' => 'Price Rate', 'fixed_rate' => 'Fixed Rate']],
                'approve_man_power' => ['label' => 'Approve Man Power', 'type' => 'number', 'rules' => 'nullable|integer|min:0'],
                'roster_shift_id' => ['label' => 'Roster Shift', 'type' => 'select', 'rules' => 'nullable|integer', 'source' => ['driver' => 'model', 'model' => Shift::class, 'label' => 'name_of_shift']],
                'is_individual_roster' => ['label' => 'Is Individual Roster', 'type' => 'checkbox', 'rules' => 'nullable|boolean'],
                'status' => ['label' => 'Status', 'type' => 'select', 'rules' => 'required|in:active,inactive', 'options' => ['active' => 'Active', 'inactive' => 'Inactive']],
            ],
        ],
        'weeks' => [
            'title' => 'Week',
            'model' => Weekday::class,
            'search' => ['name'],
            'defaults' => ['status' => 'active'],
            'index_fields' => ['name', 'day_number', 'status'],
            'fields' => [
                'name' => ['label' => 'Name', 'type' => 'text', 'rules' => 'required|string|max:50'],
                'day_number' => ['label' => 'Day Number', 'type' => 'number', 'rules' => 'nullable|integer|min:0|max:6'],
                'status' => ['label' => 'Status', 'type' => 'select', 'rules' => 'required|in:active,inactive', 'options' => ['active' => 'Active', 'inactive' => 'Inactive']],
            ],
        ],
        'working-places' => [
            'title' => 'Working Place',
            'model' => WorkingPlace::class,
            'search' => ['name', 'bn_name', 'code'],
            'defaults' => ['status' => 'active'],
            'index_fields' => ['name', 'bn_name', 'code', 'status'],
            'fields' => [
                'name' => ['label' => 'Name', 'type' => 'text', 'rules' => 'required|string|max:191'],
                'bn_name' => ['label' => 'Bangla Name', 'type' => 'text', 'rules' => 'nullable|string|max:191'],
                'code' => ['label' => 'Code', 'type' => 'text', 'rules' => 'nullable|string|max:50'],
                'address' => ['label' => 'Address', 'type' => 'textarea', 'rules' => 'nullable|string'],
                'description' => ['label' => 'Description', 'type' => 'textarea', 'rules' => 'nullable|string'],
                'status' => ['label' => 'Status', 'type' => 'select', 'rules' => 'required|in:active,inactive', 'options' => ['active' => 'Active', 'inactive' => 'Inactive']],
            ],
        ],
        'requisitions' => [
            'title' => 'Requisition',
            'model' => Requisition::class,
            'search' => ['requisition_no', 'title'],
            'defaults' => ['status' => 'draft'],
            'index_fields' => ['requisition_no', 'title', 'department_id', 'quantity', 'status'],
            'fields' => [
                'requisition_no' => ['label' => 'Requisition No', 'type' => 'text', 'rules' => 'required|string|max:50'],
                'title' => ['label' => 'Title', 'type' => 'text', 'rules' => 'required|string|max:191'],
                'department_id' => ['label' => 'Department', 'type' => 'select', 'rules' => 'nullable|integer', 'source' => ['driver' => 'attribute', 'filter' => 'department']],
                'section_id' => ['label' => 'Section', 'type' => 'select', 'rules' => 'nullable|integer', 'source' => ['driver' => 'attribute', 'filter' => 'sections']],
                'designation_id' => ['label' => 'Designation', 'type' => 'select', 'rules' => 'nullable|integer', 'source' => ['driver' => 'model', 'model' => Designation::class, 'label' => 'name']],
                'quantity' => ['label' => 'Quantity', 'type' => 'number', 'rules' => 'required|integer|min:1'],
                'requisition_date' => ['label' => 'Requisition Date', 'type' => 'date', 'rules' => 'nullable|date'],
                'requested_by' => ['label' => 'Requested By', 'type' => 'select', 'rules' => 'nullable|integer', 'source' => ['driver' => 'user', 'label' => 'name']],
                'notes' => ['label' => 'Notes', 'type' => 'textarea', 'rules' => 'nullable|string'],
                'status' => ['label' => 'Status', 'type' => 'select', 'rules' => 'required|in:draft,pending,approved,rejected', 'options' => ['draft' => 'Draft', 'pending' => 'Pending', 'approved' => 'Approved', 'rejected' => 'Rejected']],
            ],
        ],
    ],
    'reports' => [
        'employee' => 'Employee',
        'monthly' => 'Monthly',
        'machine-id' => 'Machine Id',
        'job-card' => 'Job Card',
        'personal-file' => 'Personal File',
        'attendance' => 'Attendance',
        'tiffin-night-dinner' => 'Tiffin / Night / Dinner',
        'pro-job-card' => 'Production Job Card',
        'bonus-salary-fixed' => 'Bonus Salary Fixed',
        'bonus-salary-production' => 'Bonus Salary Production',
        'salary-fixed' => 'Salary Fixed',
        'salary-production' => 'Salary Production',
        'salary-summary' => 'Wages And Salary Summary',
    ],
];
